### ISSUE TITLE
Global setup options on the service registration

### ISSUE THREAD

**Issue by arivera12** [Basaingeal/Razor.SweetAlert2#1409]
**Is your feature request related to a problem? Please describe.**
Yes, I need to setup globally `HeightAuto = false` since this breaks pages using flex and height 100%.

This is my case as specified in sweet alert 2

![image](https://user-images.githubusercontent.com/5600102/120152791-ecc04200-c1bb-11eb-8d2b-906058c43034.png)

**Describe the solution you'd like**
Global options setup in the `services.AddSweetAlert2()`;

**Describe alternatives you've considered**
What I have done for now is refactor the methods using `FireAsync`.

Used the overload method with the sweet alert options and force `HeightAuto = false`.

**Additional context**
N/A

It's seems to be possible using `Swal.mixin({ ...options })` 

https://sweetalert2.github.io/#configuration

I searched the source code and there is no overload here

https://github.com/Basaingeal/Razor.SweetAlert2/blob/develop/ExtensionMethods.cs

**Comment by Basaingeal** [comment]
This is an interesting suggestion. I'll consider it for the next major version to coincide with `sweetalert2@11`.

For now, I'd recommend using the `Swal.Mixin({})`, as this is the sort of use case it was created for. `Swal.Mixin({})` creates a `SweetAlertMixin` object that you can call FireAsync() off of, with whatever options you pass in when the mixin was created.

**Comment by arivera12** [comment]
How does `Swal.Mixin({})` affects the current swal? 

I used `Swal.Mixin({})` yesterday and it works but makes useless the `SweetAlertService` current instance since `SweetAlertService` doesn't hold the option set up on `SweetAlertMixin`

**Comment by arivera12** [comment]
I am using hardly the `SweetAlertService` and this would make me go a fix it over thousand of files. It doesn't seems a good way for me. 😢

**Comment by Basaingeal** [comment]
Something you could try perhaps. Create your own scoped service called `HeightAutoFalseSweetAlertService` or something similar.

Inject my `SweetAlertService` in the constructor. Create the mixin you want. Store it in a local variable of the service class. Then create a `FireAsync` method that just passes the config object through to your mixin.

Then, in your components, replace `@inject SweetAlertService Swal;` with `@inject HeightAutoFalseSweetAlertService Swal;`

**Comment by arivera12** [comment]
I see but still needs to be replaced on all components. 

Why can't we have that mixing option in the `services.AddSweetAlert2();`?
 
I haven't read all the source code but does this will take huge refactorization?

This is what we need to expose

https://github.com/Basaingeal/Razor.SweetAlert2/blob/75037f62e56635686775cb245ae5f4b814fa4d04/Services/SweetAlertMixin.cs#L341

**Comment by Basaingeal** [comment]
I won't be exposing that method, as I have no intention of extending the API beyond what is provided by the `sweetalert2` library.

I'll look into being able to set defaults at Startup, but that will come with `v5`

**Comment by arivera12** [comment]
I took a deep look into the source code.

I think we just need to overload  `AddSweetAlert2` with `SweetAlertOptions` and  `SweetAlertService` constructor with `SweetAlertOptions` and chain down those settings.

**Comment by Basaingeal** [comment]
This feature has been added in the v5.0.0 release. (https://github.com/Basaingeal/Razor.SweetAlert2/pull/1446) (https://github.com/Basaingeal/Razor.SweetAlert2/pull/1437)

See the [README](https://github.com/Basaingeal/Razor.SweetAlert2#default-settings) for more details.

**Comment by arivera12** [comment]
@Basaingeal The MVP!

**Comment by arivera12** [comment]
The global options are not working it's still setting the auto height

![image](https://user-images.githubusercontent.com/5600102/122630729-04406b80-d094-11eb-824e-e88b33048b97.png)

![image](https://user-images.githubusercontent.com/5600102/122630736-0c98a680-d094-11eb-9bb1-78f904b0aff4.png)

**Comment by Basaingeal** [comment]
Can you share the method call that is resulting in this? Your FireAsync call and the SweetAlertOptions that are being passed in?

**Comment by arivera12** [comment]
`await SweetAlertService.FireAsync(null, ResourceManagerLocalizer[Response?.Response?.Message ?? "TransactionCompletedSuccessfully"], SweetAlertIcon.Success);`

**Comment by arivera12** [comment]
![image](https://user-images.githubusercontent.com/5600102/122631947-520da180-d09d-11eb-801c-5795949f482e.png)

**Comment by arivera12** [comment]
I am not passing any options at all only title, message and icon.

**Comment by Basaingeal** [comment]
Yes. That is [documented](https://github.com/Basaingeal/Razor.SweetAlert2#default-settings) functionality. If you don't call the method with an options object on the C# side, it won't call the method with an options object on the JavaScript side.

For example `Swal.FireAsync("Hello World")` in C# interpolates to `Swal.fire("Hello World")` in JavaScript, while `Swal.FireAsync(new SweetAlertOptions("Hello World")` in C# will interpolate to `Swal.fire({title: "Hello World"})` in JavaScript. If you call a method that doesn't use options, no default options can be applied.

**Comment by arivera12** [comment]
I see. Will try again tomorrow.

**Comment by arivera12** [comment]
It worked! Thanks!
