### ISSUE TITLE
Can't inject 'SweetAlertService' on Razor Component

### ISSUE THREAD

**Issue by HPnavalhas** [Basaingeal/Razor.SweetAlert2#1479]
Followed the Instalation/Usage Guide:

- Installed the package via NuGet Package Manager
- Added the service to Startup.cs
- Added the script to _Host.cshtml

When trying to inject the dependecy I get:

![image](https://user-images.githubusercontent.com/86824625/124239671-d9cdc400-db11-11eb-9336-c6c99ac49892.png)

**Comment by Basaingeal** [comment]
This could be clarified in the README. You need a using directive for the file, just like any C# code referencing a library.

So above you `@inject` line add this

```razor
@using CurrieTechnologies.Razor.SweetAlert2
```

You can also add it to you _Imports.razor file to import it globally and not need it in your individual files.
