### ISSUE TITLE
.Net 6 Support

### ISSUE THREAD

**Issue by loganmarshall1** [Basaingeal/Razor.SweetAlert2#1637]
Hi There! We Love your Sweet Alert 2 for Blazor Project! Its Very helpful and useful!  Just wondering if the below nuget is compatible with .Net 6? if not, will it be by the time .Net 6 releases early November 2021?

![image](https://user-images.githubusercontent.com/19997240/137376045-dabec52d-bd77-4607-8989-fb803992d65c.png)

**Comment by Basaingeal** [comment]
Yes, .NET 6 support will arrive by the time it hits general availability.

**Comment by Basaingeal** [comment]
.NET 6 and the Razor dependency libraries released today. Needed that in order to pass build validation. Should have .NET 6 support out in a couple hours.

**Comment by Basaingeal** [comment]
.NET 6 Support is now live in v5.1.0
