### ISSUE TITLE
showloadingAsync loading text

### ISSUE THREAD

**Issue by z-elmasry** [Basaingeal/Razor.SweetAlert2#2280]
I really would like to add a "Loading Please wait..." text option to ShowLoadingAsync() can you tell me how can I do it in blazor if this option is already implemented
https://github.com/Basaingeal/Razor.SweetAlert2/blob/develop/Services/SweetAlertService.cs

**Comment by Basaingeal** [comment]
ShowLoadingAsync() just replaces the buttons with a loader. You still have access to the normal Swal options. So, you can call FireAsync() with the message you want, and then call ShowLoadingAsync() in the WillOpen callback to get the loader to show.

**Comment by z-elmasry** [comment]
Okay I tried this:
 ` 
 Swal.FireAsync("Loading Please wait...");
        Swal.ShowLoadingAsync();
        //AddUsers
        Task t = Task.Run(() => insertBook());

        t.ContinueWith((t) =>
        {
            Swal.CloseAsync();
            toastService.ShowSuccess("I'm a SUCCESS message with a custom title");
        });
`
and it's working like I wanted thanks @Basaingeal
