### ISSUE TITLE
Blazor web app in NET Core 8

### ISSUE THREAD

**Issue by abcdata2010** [Basaingeal/Razor.SweetAlert2#2631]
The Sweetalert2 v5.5.0 works fine in Blazor Server app in NET Core 8. But In Blazor web app in NET Core 8 the error is
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at sweetAlert2.min.js:1:69148
    at sweetAlert2.min.js:1:69186
    at sweetAlert2.min.js:1:70882
    at sweetAlert2.min.js:1:70886
Are there any plans to support the Blazor web app in NET Core 8?

**Comment by Basaingeal** [comment]
.NET 8 support has been added.
