### ISSUE TITLE
onOpen and showLoading 

### ISSUE THREAD

**Issue by ioer2008** [Basaingeal/Razor.SweetAlert2#755]
How can I call this?

onOpen: function() {

Swal.showLoading ()

}

**Comment by Basaingeal** [comment]
This would likely be the most concise way.

```cs
var options = new SweetAlertOptions
{
    OnOpen = new SweetAlertCallback(async () => { await Swal.ShowLoadingAsync(); }, this)
};
```

There's a bit more information on callback functions [here](https://github.com/Basaingeal/Razor.SweetAlert2#notable-differences-from-the-javascript-library).

**Comment by ioer2008** [comment]
thants
