### ISSUE TITLE
Provide a config option to remove the use of "swal2-height-auto" in Swal2's CSS

### ISSUE THREAD

**Issue by shawty** [Basaingeal/Razor.SweetAlert2#816]
When Swal2 pops open it's dialog, it places 2 class names on the document body, one of which is the "swal2-height-auto" class.

In some layouts, this is undesirable, as it breaks the layout.  By way of an example, I'm currently working on an app that has a fixed height, with inner scrolling area layout.  It looks like this:

![image](https://user-images.githubusercontent.com/1876454/88095320-d2293f80-cb8c-11ea-8057-ba2900670534.png)

When I open a Swal2 dialog however

![image](https://user-images.githubusercontent.com/1876454/88095445-0f8dcd00-cb8d-11ea-8004-8e3a41940a2f.png)

The footer bar is moved to the bottom of the content instead of remaining at the bottom of the screen where the green arrow is pointing.

As can be seen in the web-dev tools:

![image](https://user-images.githubusercontent.com/1876454/88095561-3d731180-cb8d-11ea-8626-c93979f17d7f.png)

the height auto class is applied.

If I use the dev-tools to remove the class

![image](https://user-images.githubusercontent.com/1876454/88095645-5b407680-cb8d-11ea-990a-261a5e886e03.png)

The footer returns to the bottom, but the swal display still remains ok.

![image](https://user-images.githubusercontent.com/1876454/88095784-904cc900-cb8d-11ea-9561-2c2121ff074e.png)

Being able to control this classes use in the options for Swal2 would be advantageous.

**Comment by Basaingeal** [comment]
This appears to be the behavior of the SweetAlert2 JavaScript library. This library is just a wrapper to call the JavaScript library with a C# interface in Blazor.

Please raise an issue in the https://github.com/sweetalert2/sweetalert2 repo.

**Comment by shawty** [comment]
No worries.

You could still offer a config option in the blazor library though?

I've actually managed to work around it by including a CSS file right at the end of my Blazor host file that contains this

```
body.swal2-height-auto {
  height: 100% !important
}
```

If the blazor lib had a config option that could enable/disable this simple rule after SWAL's main CSS was loaded, then that would solve thew problem.

**Comment by Basaingeal** [comment]
It is not my intention for this library to add or alter any functionality apart from what the upstream library offers. It is intended only as a .NET interface over the JavaScript library. Users shouldn't see any additional or different behavior than what they'd get if they'd used the JavaScript library.

**Comment by mkhamis266** [comment]
try 
<body style="height: 100vh!important;">
it works for me

**Comment by mkhamis266** [comment]
try inline style 
<body style="height: 100vh!important;"
it works for me

**Comment by mkhamis266** [comment]
try inline style 
body style="height: 100vh!important;"
it works for me

**Comment by FacuRodriJ** [comment]
Try adding this to the end of the document.
`<script>
        document.body.classList.remove('swal2-height-auto');
</script>
`

**Comment by Bilge** [comment]
For anyone coming from Google, this was fixed two years prior to the creation of the issue, at least in the upstream library.

See: https://github.com/sweetalert2/sweetalert2/issues/1111#issuecomment-392320575

**Comment by joaohenriquejh** [comment]
Hi, can you solve this by declaring this 
Swal.fire({
            heightAuto: false,
            title: 'Are you sure?'
            });
