### ISSUE TITLE
How Can add date input type ?

### ISSUE THREAD

**Issue by ioer2008** [Basaingeal/Razor.SweetAlert2#886]

**Comment by Basaingeal** [comment]
I don't believe date inputs are supported by the JavaScript SweetAlert2 library.

From the SweetAlert2 docs:

> Input field type, can be **text**, **email**, **password**, **number**, **tel,** **range**, **textarea,** **select**, **radio**, **checkbox**, **file** and **url**.

**Comment by Basaingeal** [comment]
This is the relevant issue from the SweetAlert2 repo: https://github.com/sweetalert2/sweetalert2/pull/1058

I'd recommend what the maintainer recommends and pass the date input HTML manually using the `Html` property.

**Comment by ioer2008** [comment]
Thank you !

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Michael J. Currie<mailto:notifications@github.com>
发送时间: 2020年9月10日 22:22
收件人: Basaingeal/Razor.SweetAlert2<mailto:Razor.SweetAlert2@noreply.github.com>
抄送: 郭军<mailto:ioer@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Basaingeal/Razor.SweetAlert2] How Can add date input type ? (#886)


This is the relevant issue from the SweetAlert2 repo: sweetalert2/sweetalert2#1058<https://github.com/sweetalert2/sweetalert2/pull/1058>

I'd recommend what the maintainer recommends and pass the date input HTML manually using the Html property.

―
